version: "3.8"
services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - cms-net

  backend:
    build: ./Backend
    restart: unless-stopped
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/cms
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - cms-net

  frontend:
    build: ./Frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - cms-net

volumes:
  mongo-data:

networks:
  cms-net:
    driver: bridge
